<?php


namespace App\Exceptions;

/**
 *
 * @Date 03/06/21
 */
class CoreException
{
    const COURSE_FEE_NOT_CONFIGURED = "COURSE_FEE_NOT_CONFIGURED";
    const DUPLICATE_COURSE_CODE = "DUPLICATE_COURSE_CODE";
    const DUPLICATE_SUBJECT_CODE = "DUPLICATE_SUBJECT_CODE";
    const DUPLICATE_CHAPTER_CODE = "DUPLICATE_CHAPTER_CODE";
    const DUPLICATE_CLASS_CODE = "DUPLICATE_CLASS_CODE";
    const COURSE_NOT_FOUND = "COURSE_NOT_FOUND";
    const EXAM_MODE_NOT_FOUND = "EXAM_MODE_NOT_FOUND";
    const DUPLICATE_EXAM_MODE_CODE = "DUPLICATE_EXAM_MODE_CODE";
    const CHAPTER_NOT_FOUND = "CHAPTER_NOT_FOUND";
    const SYLLABUS_NOT_FOUND = "SYLLABUS_NOT_FOUND";
    const INTEGRITY_CONSTRAINT_ERROR = "23000";
    const INVALID_RESOURCE = "INVALID_RESOURCE";
    const NOT_SUBSCRIBED = "NOT_SUBSCRIBED";
    const VALIDATION_ERRORS = "VALIDATION_ERRORS";
}
